nomeCompleto = input("Digite seu nome completo: ")
idade = input("Digite sua idade: ")
logradouro = input("Digite seu logradouro: ")
numero = input("Digite seu numero: ")
bairro = input("Digite seu bairro: ")
cidade = input("Digite sua cidade: ")
estado = input("Digite seu estado: ")

print("Dados do cliente:")
print(f"Nome completo: {nomeCompleto}\nIdade: {idade}\nEndereço: {logradouro}, {numero}\nBairro: {bairro}\nCidade: {cidade}\nEstado: {estado}")